# Generated by Django 3.1.2 on 2021-12-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='url',
            field=models.ImageField(max_length=300, upload_to='pinterest_app/Pin'),
        ),
    ]
