# Generated by Django 3.1.2 on 2021-11-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_app', '0004_auto_20211124_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
