# Generated by Django 3.1.2 on 2021-11-24 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_app', '0005_auto_20211124_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin_tags',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pin',
            name='url',
            field=models.ImageField(upload_to='pinterest_app/Pin'),
        ),
        migrations.RemoveField(
            model_name='pin_tags',
            name='pin',
        ),
        migrations.AddField(
            model_name='pin_tags',
            name='pin',
            field=models.ManyToManyField(blank=True, to='pinterest_app.Pin'),
        ),
        migrations.CreateModel(
            name='Saved_pins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_app.pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_pins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_app.pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
