# Generated by Django 3.1.2 on 2021-11-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_app', '0006_auto_20211124_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='url',
            field=models.ImageField(max_length=200, upload_to='pinterest_app/Pin'),
        ),
    ]
