# Generated by Django 3.1.2 on 2021-11-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_app', '0008_auto_20211127_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin_tags',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pinterest_app.pin_tags'),
        ),
    ]
