# Generated by Django 3.1.2 on 2021-11-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_app', '0010_auto_20211129_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='url',
            field=models.ImageField(upload_to='pinterest_app/Pin'),
        ),
    ]
